In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

# Question No :- 1

## Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
type(list_)

list

In [4]:
print(type(array_list))

<class 'numpy.ndarray'>


# Question No :- 02

## Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [7]:
for i in list_:    # for list_ 
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
array_list.dtype   # for array_list

dtype('<U1')

# Question No :- 03

In [12]:
array_list = np.array(object = list_, dtype = int)

## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [13]:
for j in list_ :     # for list_
    print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [14]:
array_list.dtype   # for array_list

dtype('int32')

# Question No :- 04

In [15]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

## Write a code to find the following characteristics of variable, num_array:

### shape

In [16]:
num_array.shape

(2, 3)

### size

In [17]:
num_array.size

6

# Question No :- 05

##  Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [22]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Question No :- 06

## Create an identity matrix of shape (5,5) using numpy functions?

In [25]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
np.eye(5).shape

(5, 5)